---
type: replica
setName: foo
default_args: -v --bind_ip 0.0.0.0 --enableMajorityReadConcern --quiet
default_version: v4.2
mongod:
    - name: host1
    - name: host2
    - name: host3

# vim: ts=4 sts=4 sw=4 et:
