---
type: replica
setName: foo
default_args: -v --bind_ip 0.0.0.0 --enableMajorityReadConcern --quiet
auth:
    user: root
    password: toor
mongod:
    - name: host1
    - name: host2
    - name: host3
    - name: host4
      rs_config:
          priority: 0
          hidden: true

# vim: ts=4 sts=4 sw=4 et:
