---
type: sharded
default_args: -v --bind_ip 0.0.0.0 --quiet
default_version: 4.2
mongoc:
    - name: config1
mongos:
    - name: router1
shards:
    - name: sh1
      type: replica
      mongod:
        - name: host1
# vim: ts=4 sts=4 sw=4 et:
